#!/usr/bin/env python3

"""(C) Copyright 2021 by Pascal Bauermeister.

See README.md for more information.

"""

import os.path
import sys

home = os.path.split(sys.argv[0])[0]
sys.path.append(os.path.join(home, 'src'))

if __name__ == "__main__":
    from src.umlsequence2.main import main
    main()
